global using RawLevelFileDataReader = NeoLemmixSharp.IO.Reading.RawFileDataReader<NeoLemmixSharp.IO.LevelFileSectionIdentifierHasher, NeoLemmixSharp.IO.LevelFileSectionIdentifier>;
global using RawStyleFileDataReader = NeoLemmixSharp.IO.Reading.RawFileDataReader<NeoLemmixSharp.IO.StyleFileSectionIdentifierHasher, NeoLemmixSharp.IO.StyleFileSectionIdentifier>;
global using RawLevelFileDataWriter = NeoLemmixSharp.IO.Writing.RawFileDataWriter<NeoLemmixSharp.IO.LevelFileSectionIdentifierHasher, NeoLemmixSharp.IO.LevelFileSectionIdentifier>;
global using RawStyleFileDataWriter = NeoLemmixSharp.IO.Writing.RawFileDataWriter<NeoLemmixSharp.IO.StyleFileSectionIdentifierHasher, NeoLemmixSharp.IO.StyleFileSectionIdentifier>;
